/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 11:47:38 GMT 2026
 */

package io.elasticjob.lite.internal.instance;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.elasticjob.lite.internal.instance.ShutdownListenerManager;
import io.elasticjob.lite.reg.zookeeper.ZookeeperConfiguration;
import io.elasticjob.lite.reg.zookeeper.ZookeeperRegistryCenter;
import org.apache.curator.framework.recipes.cache.TreeCacheEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShutdownListenerManager$InstanceShutdownStatusJobListener_ESTest extends ShutdownListenerManager$InstanceShutdownStatusJobListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ZookeeperConfiguration zookeeperConfiguration0 = new ZookeeperConfiguration("", (String) null);
      ZookeeperRegistryCenter zookeeperRegistryCenter0 = new ZookeeperRegistryCenter(zookeeperConfiguration0);
      ShutdownListenerManager shutdownListenerManager0 = new ShutdownListenerManager(zookeeperRegistryCenter0, (String) null);
      ShutdownListenerManager.InstanceShutdownStatusJobListener shutdownListenerManager_InstanceShutdownStatusJobListener0 = shutdownListenerManager0.new InstanceShutdownStatusJobListener();
      TreeCacheEvent.Type treeCacheEvent_Type0 = TreeCacheEvent.Type.CONNECTION_LOST;
      // Undeclared exception!
      try { 
        shutdownListenerManager_InstanceShutdownStatusJobListener0.dataChanged((String) null, treeCacheEvent_Type0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ZookeeperConfiguration zookeeperConfiguration0 = new ZookeeperConfiguration("gF}~", "gF}~");
      ZookeeperRegistryCenter zookeeperRegistryCenter0 = new ZookeeperRegistryCenter(zookeeperConfiguration0);
      ShutdownListenerManager shutdownListenerManager0 = new ShutdownListenerManager(zookeeperRegistryCenter0, "gF}~");
      ShutdownListenerManager.InstanceShutdownStatusJobListener shutdownListenerManager_InstanceShutdownStatusJobListener0 = shutdownListenerManager0.new InstanceShutdownStatusJobListener();
      TreeCacheEvent.Type treeCacheEvent_Type0 = TreeCacheEvent.Type.CONNECTION_RECONNECTED;
      shutdownListenerManager_InstanceShutdownStatusJobListener0.dataChanged("gF}~", treeCacheEvent_Type0, "gF}~");
  }
}
