/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 11:39:07 GMT 2026
 */

package org.apache.skywalking.apm.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ObjectInputStream;
import java.util.Properties;
import org.apache.skywalking.apm.util.ConfigInitializer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConfigInitializer_ESTest extends ConfigInitializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Boolean> class0 = Boolean.class;
      // Undeclared exception!
      try { 
        ConfigInitializer.initialize((Properties) null, class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.skywalking.apm.util.ConfigInitializer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Properties properties0 = new Properties();
      Class<ObjectInputStream> class0 = ObjectInputStream.class;
      ConfigInitializer.initialize(properties0, class0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConfigInitializer configInitializer0 = new ConfigInitializer();
  }
}
