/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 11:21:49 GMT 2026
 */

package org.jboss.as.naming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Hashtable;
import javax.naming.Binding;
import javax.naming.CompositeName;
import javax.naming.CompoundName;
import javax.naming.Name;
import javax.naming.event.EventContext;
import javax.naming.event.NamingListener;
import org.eclipse.jgit.diff.RawText;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.as.naming.InMemoryNamingStore;
import org.jboss.as.naming.NamingContext;
import org.jboss.as.naming.NamingEventCoordinator;
import org.jboss.crypto.JBossSXProvider;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NamingEventCoordinator_ESTest extends NamingEventCoordinator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      Hashtable<Integer, Object> hashtable0 = new Hashtable<Integer, Object>();
      NamingContext namingContext0 = new NamingContext(hashtable0);
      Binding binding0 = new Binding("org.jboss.as.naming.NamingEventCoordinator$TargetScope", "org.jboss.as.naming.NamingEventCoordinator$TargetScope");
      Integer[] integerArray0 = new Integer[0];
      // Undeclared exception!
      try { 
        namingEventCoordinator0.fireEvent(namingContext0, (Name) null, binding0, binding0, 1036, "org.jboss.as.naming.NamingEventCoordinator$TargetScope", integerArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      CompositeName compositeName0 = new CompositeName();
      RawText rawText0 = RawText.EMPTY_TEXT;
      Binding binding0 = new Binding("HOUR", rawText0);
      Integer[] integerArray0 = new Integer[0];
      // Undeclared exception!
      try { 
        namingEventCoordinator0.fireEvent((EventContext) null, compositeName0, binding0, binding0, 132, "HOUR", integerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // null source
         //
         verifyException("java.util.EventObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      namingEventCoordinator0.addListener("", (-1153), (NamingListener) null);
      namingEventCoordinator0.addListener((String) null, (-1153), (NamingListener) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      namingEventCoordinator0.addListener((String) null, (-1153), (NamingListener) null);
      namingEventCoordinator0.addListener("", (-1153), (NamingListener) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      namingEventCoordinator0.addListener((String) null, 165, (NamingListener) null);
      namingEventCoordinator0.addListener((String) null, 165, (NamingListener) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      JBossSXProvider jBossSXProvider0 = new JBossSXProvider();
      CompoundName compoundName0 = new CompoundName("", jBossSXProvider0);
      InMemoryNamingStore inMemoryNamingStore0 = new InMemoryNamingStore(namingEventCoordinator0, compoundName0);
      NamingContext namingContext0 = new NamingContext(inMemoryNamingStore0, jBossSXProvider0);
      Object object0 = new Object();
      Binding binding0 = new Binding("s0Gv)ly6FyrEkE7z", object0);
      Integer integer0 = new Integer(2);
      Integer[] integerArray0 = new Integer[3];
      integerArray0[0] = integer0;
      namingEventCoordinator0.fireEvent(namingContext0, compoundName0, binding0, binding0, 2, "I@v2> d]QK{]?", integerArray0);
      assertEquals(3, integerArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      CompositeName compositeName0 = new CompositeName("");
      InMemoryNamingStore inMemoryNamingStore0 = new InMemoryNamingStore(compositeName0);
      Hashtable<Integer, Integer> hashtable0 = new Hashtable<Integer, Integer>();
      NamingContext namingContext0 = new NamingContext(compositeName0, inMemoryNamingStore0, hashtable0);
      Object object0 = new Object();
      Binding binding0 = new Binding("", object0, false);
      Integer[] integerArray0 = new Integer[5];
      Integer integer0 = new Integer(1);
      integerArray0[0] = integer0;
      namingEventCoordinator0.fireEvent(namingContext0, compositeName0, binding0, binding0, (-257), "", integerArray0);
      assertEquals(5, integerArray0.length);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      CompositeName compositeName0 = new CompositeName("^0/ hhR|!M,A?e");
      InMemoryNamingStore inMemoryNamingStore0 = new InMemoryNamingStore(namingEventCoordinator0, compositeName0);
      inMemoryNamingStore0.bind((Name) compositeName0, (Object) compositeName0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      NamingListener namingListener0 = mock(NamingListener.class, new ViolatedAssumptionAnswer());
      namingEventCoordinator0.removeListener(namingListener0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      namingEventCoordinator0.addListener("mLbpu@n,(*+Q-cAR", 3, (NamingListener) null);
      namingEventCoordinator0.removeListener((NamingListener) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NamingEventCoordinator namingEventCoordinator0 = new NamingEventCoordinator();
      namingEventCoordinator0.addListener("A", 2, (NamingListener) null);
      namingEventCoordinator0.addListener("A", 2, (NamingListener) null);
  }
}
