/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 10:29:54 GMT 2026
 */

package org.jboss.as.naming;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import javax.naming.Binding;
import javax.naming.CompositeName;
import javax.naming.CompoundName;
import javax.naming.InvalidNameException;
import javax.naming.Name;
import javax.naming.NameClassPair;
import javax.naming.NamingException;
import javax.naming.event.NamingListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jboss.as.naming.NamingContext;
import org.jboss.as.naming.ServiceBasedNamingStore;
import org.jboss.as.naming.WritableServiceBasedNamingStore;
import org.jboss.msc.service.DelegatingServiceContainer;
import org.jboss.msc.service.DelegatingServiceRegistry;
import org.jboss.msc.service.ServiceName;
import org.jboss.msc.service.ServiceRegistry;
import org.jboss.msc.service.ServiceTarget;
import org.junit.runner.RunWith;
import org.wildfly.security.EmptyProvider;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ServiceBasedNamingStore_ESTest extends ServiceBasedNamingStore_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      serviceBasedNamingStore0.add(serviceName0);
      CompositeName compositeName0 = new CompositeName("r");
      try { 
        serviceBasedNamingStore0.listBindings(compositeName0);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompositeName@0000000003
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DelegatingServiceContainer delegatingServiceContainer0 = new DelegatingServiceContainer((ServiceTarget) null, (ServiceRegistry) null);
      ServiceName serviceName0 = ServiceName.parse(")*v@9&:!vT6X");
      WritableServiceBasedNamingStore writableServiceBasedNamingStore0 = new WritableServiceBasedNamingStore(delegatingServiceContainer0, serviceName0, (ServiceTarget) null);
      Name name0 = writableServiceBasedNamingStore0.getBaseName();
      ServiceName serviceName1 = ServiceName.parse(")*v@9&:!vT6X");
      writableServiceBasedNamingStore0.add(serviceName1);
      try { 
        writableServiceBasedNamingStore0.list(name0);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompositeName@0000000005
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      NamingListener namingListener0 = mock(NamingListener.class, new ViolatedAssumptionAnswer());
      serviceBasedNamingStore0.removeNamingListener(namingListener0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      ServiceRegistry serviceRegistry0 = serviceBasedNamingStore0.getServiceRegistry();
      assertNull(serviceRegistry0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, (ServiceName) null);
      ServiceName serviceName0 = serviceBasedNamingStore0.getServiceNameBase();
      assertNull(serviceName0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DelegatingServiceRegistry delegatingServiceRegistry0 = new DelegatingServiceRegistry((ServiceRegistry) null);
      WritableServiceBasedNamingStore writableServiceBasedNamingStore0 = new WritableServiceBasedNamingStore(delegatingServiceRegistry0, (ServiceName) null, (ServiceTarget) null);
      CompositeName compositeName0 = new CompositeName();
      ServiceName serviceName0 = writableServiceBasedNamingStore0.buildServiceName(compositeName0);
      assertNull(serviceName0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      CompositeName compositeName0 = new CompositeName("r");
      ServiceName serviceName1 = serviceBasedNamingStore0.buildServiceName(compositeName0);
      assertEquals("r", serviceName1.getSimpleName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.remove((ServiceName) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.concurrent.ConcurrentSkipListMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.lookup((Name) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.lookup((Name) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      String[] stringArray0 = new String[4];
      stringArray0[0] = "5";
      stringArray0[1] = "5";
      stringArray0[2] = "5";
      stringArray0[3] = "5";
      ServiceName serviceName1 = ServiceName.of(serviceName0, stringArray0);
      serviceBasedNamingStore0.add(serviceName1);
      EmptyProvider emptyProvider0 = EmptyProvider.getInstance();
      CompoundName compoundName0 = new CompoundName("5", emptyProvider0);
      try { 
        serviceBasedNamingStore0.listBindings(compoundName0);
        fail("Expecting exception: InvalidNameException");
      
      } catch(InvalidNameException e) {
         //
         // A flat name can only have a single component
         //
         verifyException("javax.naming.NameImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.listBindings((Name) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.list((Name) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, (ServiceName) null);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.getBaseName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.buildServiceName((Name) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.add((ServiceName) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.concurrent.ConcurrentSkipListMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      EmptyProvider emptyProvider0 = EmptyProvider.getInstance();
      CompoundName compoundName0 = new CompoundName("", emptyProvider0);
      NamingContext namingContext0 = (NamingContext)serviceBasedNamingStore0.lookup((Name) compoundName0, false);
      assertFalse(namingContext0.targetMustExist());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      Name name1 = serviceBasedNamingStore0.getBaseName();
      assertSame(name1, name0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.parse("http://apache.org/xml/features/internal/tolerate-duplicates");
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      CompositeName compositeName0 = new CompositeName("http://apache.org/xml/features/internal/tolerate-duplicates");
      try { 
        serviceBasedNamingStore0.lookup((Name) compositeName0);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompositeName@0000000010
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      serviceBasedNamingStore0.add(serviceName0);
      // Undeclared exception!
      try { 
        serviceBasedNamingStore0.add(serviceName0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DelegatingServiceContainer delegatingServiceContainer0 = new DelegatingServiceContainer((ServiceTarget) null, (ServiceRegistry) null);
      String[] stringArray0 = new String[8];
      stringArray0[0] = ")*v@9&:!vT6X";
      stringArray0[1] = ")*v@9&:!vT6X";
      stringArray0[2] = ")*v@9&:!vT6X";
      stringArray0[3] = ")*v@9&:!vT6X";
      stringArray0[4] = ")*v@9&:!vT6X";
      stringArray0[5] = ")*v@9&:!vT6X";
      stringArray0[6] = ")*v@9&:!vT6X";
      stringArray0[7] = ")*v@9&:!vT6X";
      ServiceName serviceName0 = ServiceName.of(stringArray0);
      ServiceName serviceName1 = serviceName0.append(stringArray0);
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore(delegatingServiceContainer0, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      serviceBasedNamingStore0.add(serviceName1);
      Name name1 = name0.add("!p");
      List<NameClassPair> list0 = serviceBasedNamingStore0.list(name1);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "SemicolonRequiredInCharRef";
      stringArray0[1] = "SemicolonRequiredInCharRef";
      stringArray0[2] = "SemicolonRequiredInCharRef";
      stringArray0[3] = "2-`xUL7JXBEjI";
      stringArray0[4] = "n(b9GR=}j1Y=dt>w/2";
      stringArray0[5] = "java:app";
      stringArray0[6] = "java:app";
      stringArray0[7] = "n(b9GR=}j1Y=dt>w/2";
      ServiceName serviceName1 = ServiceName.of(serviceName0, stringArray0);
      serviceBasedNamingStore0.add(serviceName1);
      List<Binding> list0 = serviceBasedNamingStore0.listBindings(name0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      CompositeName compositeName0 = new CompositeName("org.jboss.as.naming.ServiceBasedNamingStore$1");
      String[] stringArray0 = new String[1];
      stringArray0[0] = "org.jboss.as.naming.ServiceBasedNamingStore$1";
      ServiceName serviceName1 = ServiceName.of(serviceName0, stringArray0);
      ServiceName serviceName2 = ServiceName.of(serviceName1, stringArray0);
      serviceBasedNamingStore0.add(serviceName2);
      try { 
        serviceBasedNamingStore0.listBindings(compositeName0);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompositeName@0000000005
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      ServiceName serviceName1 = ServiceName.parse("SemicolonRequiredInCharRef");
      serviceBasedNamingStore0.add(serviceName1);
      List<Binding> list0 = serviceBasedNamingStore0.listBindings(name0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "SemicolonRequiredInCharRef";
      stringArray0[1] = "SemicolonRequiredInCharRef";
      stringArray0[2] = "SemicolonRequiredInCharRef";
      stringArray0[3] = "2-`xUL7JXBEjI";
      stringArray0[4] = "n(b9GR=}j1Y=dt>w/2";
      stringArray0[5] = "java:app";
      stringArray0[6] = "java:app";
      stringArray0[7] = "n(b9GR=}j1Y=dt>w/2";
      ServiceName serviceName1 = ServiceName.of(serviceName0, stringArray0);
      serviceBasedNamingStore0.add(serviceName1);
      List<NameClassPair> list0 = serviceBasedNamingStore0.list(name0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.parse("SemicolonRequiredInCharRef");
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "SemicolonRequiredInCharRef";
      ServiceName serviceName1 = ServiceName.of(serviceName0, stringArray0);
      serviceBasedNamingStore0.add(serviceName1);
      try { 
        serviceBasedNamingStore0.list(name0);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompositeName@0000000004
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      ServiceName serviceName1 = ServiceName.parse("SemicolonRequiredInCharRef");
      serviceBasedNamingStore0.add(serviceName1);
      List<NameClassPair> list0 = serviceBasedNamingStore0.list(name0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      EmptyProvider emptyProvider0 = EmptyProvider.getInstance();
      CompoundName compoundName0 = new CompoundName("!y9-tg", emptyProvider0);
      try { 
        serviceBasedNamingStore0.lookup((Name) compoundName0, true);
        fail("Expecting exception: NamingException");
      
      } catch(NamingException e) {
         //
         // WFLYNAM0062: Failed to lookup javax.naming.CompoundName@0000000003
         //
         verifyException("org.jboss.as.naming.ServiceBasedNamingStore", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      ServiceName serviceName1 = serviceBasedNamingStore0.getServiceNameBase();
      assertSame(serviceName0, serviceName1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      NamingContext namingContext0 = (NamingContext)serviceBasedNamingStore0.lookup(name0);
      assertFalse(namingContext0.targetMustExist());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DelegatingServiceContainer delegatingServiceContainer0 = new DelegatingServiceContainer((ServiceTarget) null, (ServiceRegistry) null);
      String[] stringArray0 = new String[8];
      stringArray0[0] = ")*v@9&:!vT6X";
      stringArray0[1] = ")*v@9&:!vT6X";
      stringArray0[2] = ")*v@9&:!vT6X";
      stringArray0[3] = ")*v@9&:!vT6X";
      stringArray0[4] = ")*v@9&:!vT6X";
      stringArray0[5] = ")*v@9&:!vT6X";
      stringArray0[6] = ")*v@9&:!vT6X";
      stringArray0[7] = ")*v@9&:!vT6X";
      ServiceName serviceName0 = ServiceName.of(stringArray0);
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore(delegatingServiceContainer0, serviceName0);
      serviceBasedNamingStore0.close();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DelegatingServiceContainer delegatingServiceContainer0 = new DelegatingServiceContainer((ServiceTarget) null, (ServiceRegistry) null);
      String[] stringArray0 = new String[8];
      stringArray0[0] = ")*v@9&:!vT6X";
      stringArray0[1] = ")*v@9&:!vT6X";
      stringArray0[2] = ")*v@9&:!vT6X";
      stringArray0[3] = ")*v@9&:!vT6X";
      stringArray0[4] = ")*v@9&:!vT6X";
      stringArray0[5] = ")*v@9&:!vT6X";
      stringArray0[6] = ")*v@9&:!vT6X";
      stringArray0[7] = ")*v@9&:!vT6X";
      ServiceName serviceName0 = ServiceName.of(stringArray0);
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore(delegatingServiceContainer0, serviceName0);
      ServiceRegistry serviceRegistry0 = serviceBasedNamingStore0.getServiceRegistry();
      assertSame(delegatingServiceContainer0, serviceRegistry0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DelegatingServiceContainer delegatingServiceContainer0 = new DelegatingServiceContainer((ServiceTarget) null, (ServiceRegistry) null);
      String[] stringArray0 = new String[8];
      stringArray0[0] = ")*v@9&:!vT6X";
      stringArray0[1] = ")*v@9&:!vT6X";
      stringArray0[2] = ")*v@9&:!vT6X";
      stringArray0[3] = ")*v@9&:!vT6X";
      stringArray0[4] = ")*v@9&:!vT6X";
      stringArray0[5] = ")*v@9&:!vT6X";
      stringArray0[6] = ")*v@9&:!vT6X";
      stringArray0[7] = ")*v@9&:!vT6X";
      ServiceName serviceName0 = ServiceName.of(stringArray0);
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore(delegatingServiceContainer0, serviceName0);
      Name name0 = serviceBasedNamingStore0.getBaseName();
      NamingListener namingListener0 = mock(NamingListener.class, new ViolatedAssumptionAnswer());
      serviceBasedNamingStore0.addNamingListener(name0, 2460, namingListener0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ServiceName serviceName0 = ServiceName.JBOSS;
      ServiceBasedNamingStore serviceBasedNamingStore0 = new ServiceBasedNamingStore((ServiceRegistry) null, serviceName0);
      serviceBasedNamingStore0.remove(serviceName0);
      assertEquals(1, serviceName0.length());
  }
}
